# Broadcasting

In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = 10

print(a + b)  

[11 12 13]


# View

In [6]:
arr = np.array([1, 2, 3])
print(arr[0:2])
view = arr[0:2]
print(view)
view[0] = 100

print(arr) 


[1 2]
[1 2]
[100   2   3]


# Indexing and Slicing 

In [10]:
arr=np.array([1,2,3,4,5,8])
print(arr[0]) #1st element
print(arr[-1]) #From last
print(arr[1:3]) # 1-2 slicing

1
8
[2 3]


# Broadcasting

In [18]:
a=np.array([1,2,3,4,5,6,7,7])
b=23
print (a+b)
d=np.array ([1,2,3])
c=np.array([[10,20,30],
            [30,50,60]])
print(c+d)

[24 25 26 27 28 29 30 30]
[[11 22 33]
 [31 52 63]]


# Boolean Indexing

In [21]:
a=np.array([10,20,30,50,80,130,210])
print(a>=50) #checks which elements are greater than 50
print(a[a>=50])

[False False False  True  True  True  True]
[ 50  80 130 210]


# Element wise op

In [30]:
a=np.array([1,3,6,7,9])
b=np.array([2,4,5,8,10])
c=np.array([[10,20,30,40,50],
           [100,200,300,400,500]])
print(a+b)
print(a+c)
print(c>40)
print(c[c<300])
print(a*b)
print(a**b)
print(a//b)
print(a%b)
print(a<b)
print(a==b)

[ 3  7 11 15 19]
[[ 11  23  36  47  59]
 [101 203 306 407 509]]
[[False False False False  True]
 [ True  True  True  True  True]]
[ 10  20  30  40  50 100 200]
[ 2 12 30 56 90]
[         1         81       7776    5764801 3486784401]
[0 0 1 0 0]
[1 3 1 7 9]
[ True  True False  True  True]
[False False False False False]


# Functions

In [32]:
a=np.array([46,6,63,49,21,72,20,60,72,])
print(a)
print(a.min())    #smallest element
print(a.max())    #largest elm
print(a.argmin())   #position of min
print(a.argmax()) #position of max

[46  6 63 49 21 72 20 60 72]
6
72
1
5


# Task 1

In [34]:
a=np.arange(1,21)
print (a)
print(a[0:6])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[1 2 3 4 5 6]


# Task 2

In [37]:
a=np.arange(1,17)
print(a)
ab=a.reshape(4,4)
print(ab)
c=np.diag(ab)
print(c)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  6 11 16]


# Task 3

In [45]:
a=np.random.randint(-50,50,size=20)
print(a)
b=a[0:]
b[b<0]=0
print(a)


[ 41 -31  14 -40  -3 -46  43  20 -49  31   3 -25  24  32  29   8 -43  25
 -16 -25]
[41  0 14  0  0  0 43 20  0 31  3  0 24 32 29  8  0 25  0  0]


# Task 4

In [46]:
a=np.zeros((10,10),dtype=int)
print(a)
a[0,:]=1
a[-1,:]=1
a[:,0]=1
a[:,-1]=1
print(a)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


# Task 5

In [47]:
a=np.random.randint(1,51,size=25)
print(a)
a=a.reshape(5,5)
print(a)
a[a>25]=99
print(a)

[11 38  1  8  1 33 28  8 10 39 24 33 16 38 30 39 26 37  8 11 43 28 42 24
 32]
[[11 38  1  8  1]
 [33 28  8 10 39]
 [24 33 16 38 30]
 [39 26 37  8 11]
 [43 28 42 24 32]]
[[11 99  1  8  1]
 [99 99  8 10 99]
 [24 99 16 99 99]
 [99 99 99  8 11]
 [99 99 99 24 99]]
