# Task 1

In [1]:
import numpy as np
a=np.arange(1,13)
a=a.reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Task 2

In [2]:
a=np.arange(1,7)
a=a.reshape(2,3)
a=a.transpose ()
print(a)

[[1 4]
 [2 5]
 [3 6]]


# Task 3

In [3]:
a=np.arange(0,30)
a=a.reshape(6,5)
print(a)
print(a[:,2])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[ 2  7 12 17 22 27]


# Task 4

In [4]:
a=np.arange(1,10)
a=a.reshape(3,3)
print(a)
a=a.ravel()
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


# Task 5

In [9]:
a=np.zeros((8,8),dtype=int)
print(a)
print()
a[::2, ::2] = 1
a[1::2,1::2]=1
print(a)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


## head