# TASK 1

In [2]:
import numpy as np
a=np.random.randint(1,101,size=30)
print(a)

[ 3 72 16 50 52 27 52 17 11 19 72 27 38 91 72 55 42 70 17 65 90 85 61 96
 36  8 70 28 87 68]


# TASK 2

In [6]:
c=a.sum()
print(c)
print(a.mean())
print(a.std())


1388
46.266666666666666
26.19787947313463


# TASK 3

In [8]:
b=np.eye(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# TASK 4

In [23]:
t4=np.random.randint(1,21,size=5)
print(t4)

[12  1  7 11 16]


# TASK 5

In [29]:
t5=np.random.randint(1,100,size=(5,5))
print(t5)
print(t5.sum())
print(t5.mean())
print(t5.std())

[[55 75 36  6 75]
 [60 80 58 95 44]
 [85 72 92 31 55]
 [30 93 27 61 26]
 [16 38 92 22 37]]
1361
54.44
26.374351176853622


# TASK 6

In [41]:
a=np.random.randint(1,10,size=100)
print(a)
b=np.bincount(a)
print(b)
print("most frequent:",np.argmax(b))

[6 3 8 3 9 6 4 6 3 2 5 1 3 2 8 9 3 7 9 6 8 7 6 2 5 8 2 2 1 1 8 6 4 4 6 3 3
 4 2 8 3 1 2 7 7 2 9 3 2 2 2 1 6 6 4 5 8 5 2 8 4 6 1 9 8 4 6 7 2 6 3 3 7 5
 5 5 8 5 5 7 6 9 2 6 2 1 8 1 5 9 8 9 7 4 9 7 7 3 1 8]
[ 0  9 15 12  8 10 14 10 13  9]
most frequent: 2


In [10]:
np
a=np.random.randint(1,30,size=(5,5))
a[np.diag_indices(2)]=5
print(a)


[[ 5 29 18  2 11]
 [ 5  5 19  2  6]
 [ 6  4 14  4 13]
 [17 11  5  4 17]
 [25 25 22 22 12]]


# TASK 7

In [44]:
a=np.random.randint(1,100,size=(4,4))
print(a)
b=(((a-a.min())/(a.max()-a.min())))
print(b)

[[ 2 81 45  5]
 [92 91 96 29]
 [41 65 16 30]
 [78 41 45 46]]
[[0.         0.84042553 0.45744681 0.03191489]
 [0.95744681 0.94680851 1.         0.28723404]
 [0.41489362 0.67021277 0.14893617 0.29787234]
 [0.80851064 0.41489362 0.45744681 0.46808511]]


# TASK 8

In [50]:
a=np.random.randint(1,10,size=(3,3))
print(a)
print()
b=np.random.randint(1,10,size=(3,3))
print()
print(b)
print()
print(a*b)
print()
print(np.dot(a,b))
print()
print(a@b)
print(a.T)
print(np.linalg.det(a))
print(np.linalg.inv(a))
print(np.linalg.matrix_rank(a))
print(np.linalg.eig(a))

[[7 1 8]
 [3 9 2]
 [3 1 6]]


[[7 1 6]
 [1 7 9]
 [7 6 5]]

[[49  1 48]
 [ 3 63 18]
 [21  6 30]]

[[106  62  91]
 [ 44  78 109]
 [ 64  46  57]]

[[106  62  91]
 [ 44  78 109]
 [ 64  46  57]]
[[7 3 3]
 [1 9 1]
 [8 2 6]]
159.99999999999994
[[ 0.325   0.0125 -0.4375]
 [-0.075   0.1125  0.0625]
 [-0.15   -0.025   0.375 ]]
3
EigResult(eigenvalues=array([12.85617408,  1.66381978,  7.48000614]), eigenvectors=array([[-0.62779305, -0.827082  ,  0.37345271],
       [-0.68250772,  0.19444627, -0.91746351],
       [-0.37424471,  0.52737654,  0.13709039]]))
