# Task 0

In [2]:
import numpy as np

# Rows = students, Columns = subjects
grades = np.array([
    [85, 78, 92, 74],   # Student 1
    [88, 90, 76, 95],   # Student 2
    [70, 65, 80, 72],   # Student 3
    [95, 98, 94, 99],   # Student 4
    [60, 75, 68, 70]    # Student 5
])

print("Grades:\n", grades)

a=np.mean(grades,axis=1)
print(a)
b=np.mean(grades,axis=0)
print(b)

Grades:
 [[85 78 92 74]
 [88 90 76 95]
 [70 65 80 72]
 [95 98 94 99]
 [60 75 68 70]]
[82.25 87.25 71.75 96.5  68.25]
[79.6 81.2 82.  82. ]


# TASK 1

In [8]:
a=np.arange(0,16)
a=a.reshape(4,4)
b=np.arange(17,33)
b=b.reshape(4,4)
c=np.hstack((a,b))
print(c)

[[ 0  1  2  3 17 18 19 20]
 [ 4  5  6  7 21 22 23 24]
 [ 8  9 10 11 25 26 27 28]
 [12 13 14 15 29 30 31 32]]


In [9]:
a=np.arange(0,16)
a=a.reshape(4,4)
b=np.arange(17,33)
b=b.reshape(4,4)
c=np.vstack((a,b))
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


# TASK 2

In [13]:
a=np.arange(16)
b=np.split(a,2)
print(b)

[array([0, 1, 2, 3, 4, 5, 6, 7]), array([ 8,  9, 10, 11, 12, 13, 14, 15])]


In [14]:
a=np.arange(8)
a=a.reshape(2,2,2)
print(a)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


# TASK 3

In [17]:
a=np.arange(30)
b=a #creates a view if we change 'b' ,'a' will also change
b[1]=100
print(a)
c=np.copy(a) #creates a copy , changes made in 'c' does not affect 'a'
c[10]=100
print(c)
print(a)

[  0 100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29]
[  0 100   2   3   4   5   6   7   8   9 100  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29]
[  0 100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29]


# TASK 4

In [6]:
#concatenate
a=np.arange(16)
b=np.random.randint(30,60,size=16)
c=np.concatenate((a,b),axis=0)
print(c)
#vstack
d=np.vstack((a,b))
print(d)
#hstack
e=np.hstack((a,b))
print(e)
#stack
f=np.stack((a,b),axis=1)
print(f)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 37 42 48 36 47 38 47 51
 39 32 53 54 52 30 39 55]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [37 42 48 36 47 38 47 51 39 32 53 54 52 30 39 55]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 37 42 48 36 47 38 47 51
 39 32 53 54 52 30 39 55]
[[ 0 37]
 [ 1 42]
 [ 2 48]
 [ 3 36]
 [ 4 47]
 [ 5 38]
 [ 6 47]
 [ 7 51]
 [ 8 39]
 [ 9 32]
 [10 53]
 [11 54]
 [12 52]
 [13 30]
 [14 39]
 [15 55]]


In [34]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate((a,b)))
print(np.vstack((a,b)))
print(np.hstack((a,b)))
print(np.stack((a,b),axis=1))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


# TASK 5

In [39]:
a=np.eye(3)
b=np.vstack((a,a))
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# TASK 6

In [7]:
a=np.random.randint(1,50,size=20)
b=np.split(a,4)
print(a)
print(b)

[17 23 21 45 24 20 20 15 20 23 13 42 33 47 21 35 21  8 36 20]
[array([17, 23, 21, 45, 24], dtype=int32), array([20, 20, 15, 20, 23], dtype=int32), array([13, 42, 33, 47, 21], dtype=int32), array([35, 21,  8, 36, 20], dtype=int32)]


# TASK 7

In [49]:
a=np.arange(20)
b=a
b[1]=85
print(a)
print(b)
c=a.copy()
c[1]=2
print(a)
print(c)

[ 0 85  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0 85  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0 85  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# TASK 8

In [53]:
a=np.random.randint(100,size=(2,3))
b=np.random.randint(100,size=(2,3))
print(a)
print(b)
c=np.hstack((a,b))
print(c)

[[13 52  2]
 [35 93 52]]
[[87 95 29]
 [42 34 94]]
[[13 52  2 87 95 29]
 [35 93 52 42 34 94]]
