In [1]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)

[[1 2 3]
 [4 5 6]]


In [2]:
arr2=np.arange(1,7).reshape(2,3)
print(arr2)

[[1 2 3]
 [4 5 6]]


In [8]:
arr3=np.zeros((1,7))
print(arr3)

[[0. 0. 0. 0. 0. 0. 0.]]


In [14]:
a=np.ones((1,3),dtype=int)
print(a)
print(a.shape)
print(a.size)
print(a.dtype)

[[1 1 1]]
(1, 3)
3
int64


In [15]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [10]:
a=np.arange(20,41,2)
print(a)
print(a*2)

[20 22 24 26 28 30 32 34 36 38 40]
[40 44 48 52 56 60 64 68 72 76 80]


In [24]:
a=np.random.randint(1,51,20)
print(a)
print(a[a%2!=0])

[24 34  1 40 14 23 44 30 36 36  2  3 32 49 13 37 29 44 37  2]
[ 1 23  3 49 13 37 29 37]


In [25]:
a=np.arange(1,37).reshape(6,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [34]:
a=np.random.randint(1,30,size=(2,2))
print(a)
print(a[0:1,1:2])

[[20  5]
 [ 2 13]]
[[5]]


In [41]:
a=np.arange(1,50).reshape(7,7)
print(a)
print()
print(a[3:4,3:4])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]

[[25]]


In [50]:
a=np.random.randint(1,50,size=(4,4))
print(a)
print((np.fill_diagonal(a,5)))
print(a)
print(np.diag(a))

[[45 26 10 20]
 [19  6  3  2]
 [27 19 23 15]
 [34 12  6 40]]
None
[[ 5 26 10 20]
 [19  5  3  2]
 [27 19  5 15]
 [34 12  6  5]]
[5 5 5 5]


In [52]:
a=np.random.randint(-50,50,size=50)
a[a<0]=0
print(a)

[33  0 15 13  0 41  1  0  0 49  0  0  0  0 31  1 16 34 40  0  0  0 16 21
  0 26 22  0  0 23 21  8  0  0 44  6 19  0 48 15  0 14  0  0 30  0  5  0
  0  0]


In [63]:
a=np.random.randint(1,100,size=(10,10))
a[0]=1
print(a)
print()
a[-1]=1
print(a)
a[:,0]=1
a[:,-1]=1
print(a)
a[1:9,1:9]=0
print(a)


[[ 1  1  1  1  1  1  1  1  1  1]
 [55 52 32 76 65 58 86 12 31 23]
 [91 81 30 98 55 42 62  7 19 30]
 [13 51 52 11 30  7 16 62 59 11]
 [77 41 16 87  7 80 14 45 32 88]
 [70 90  8 66 83 45 67  5 62 98]
 [79 82 67 72 10 17 78 51 86 89]
 [43 21 24 30 49 74 59 41 28 50]
 [43 29 70 55  1 76 39 77 84 82]
 [88 26 30  9 86 65 12 82 92 78]]

[[ 1  1  1  1  1  1  1  1  1  1]
 [55 52 32 76 65 58 86 12 31 23]
 [91 81 30 98 55 42 62  7 19 30]
 [13 51 52 11 30  7 16 62 59 11]
 [77 41 16 87  7 80 14 45 32 88]
 [70 90  8 66 83 45 67  5 62 98]
 [79 82 67 72 10 17 78 51 86 89]
 [43 21 24 30 49 74 59 41 28 50]
 [43 29 70 55  1 76 39 77 84 82]
 [ 1  1  1  1  1  1  1  1  1  1]]
[[ 1  1  1  1  1  1  1  1  1  1]
 [ 1 52 32 76 65 58 86 12 31  1]
 [ 1 81 30 98 55 42 62  7 19  1]
 [ 1 51 52 11 30  7 16 62 59  1]
 [ 1 41 16 87  7 80 14 45 32  1]
 [ 1 90  8 66 83 45 67  5 62  1]
 [ 1 82 67 72 10 17 78 51 86  1]
 [ 1 21 24 30 49 74 59 41 28  1]
 [ 1 29 70 55  1 76 39 77 84  1]
 [ 1  1  1  1  1  1  1  1  1  1]]
[[1 1 

In [70]:
a=np.random.randint(1,50,size=(5,5))
print(a)
a[a>25]=99
print()
print(a)
a=a.flatten()
print(a)

[[29  3 17 26 36]
 [21 29 18 24 27]
 [23  1 17 33  6]
 [30 10 13 28 47]
 [22 46  3 40 28]]

[[99  3 17 99 99]
 [21 99 18 24 99]
 [23  1 17 99  6]
 [99 10 13 99 99]
 [22 99  3 99 99]]
[99  3 17 99 99 21 99 18 24 99 23  1 17 99  6 99 10 13 99 99 22 99  3 99
 99]


In [71]:
a=np.random.randint(1,50,size=(3,4))
print(a)
print(np.transpose(a))

[[40  5 15 29]
 [19 10 13 36]
 [43 43  3  6]]
[[40 19 43]
 [ 5 10 43]
 [15 13  3]
 [29 36  6]]


In [8]:
a=np.linspace(5,25,15)
print(a)

[ 5.          6.42857143  7.85714286  9.28571429 10.71428571 12.14285714
 13.57142857 15.         16.42857143 17.85714286 19.28571429 20.71428571
 22.14285714 23.57142857 25.        ]


In [9]:
a=np.random.randint(50,100,size=(4,4))
print(a)

[[98 51 92 56]
 [59 65 56 95]
 [99 88 92 50]
 [69 56 96 72]]


In [14]:
a=np.random.randint(1,5,size=(2,3))
b=np.random.randint(1,10,size=(1,2))
print(b@a)

[[16 15 10]]
